#!/bin/bash
#############################################################################
# Program : Make it tool
# Author : Chauncey Yan
# Description : shoot the code to the /tool/bin
# Revision : 1.0
# Date : May 22st
# Update : 
# Known issue : 
#############################################################################
filename=`echo $1 | awk -F'/' '{print $NF}'`
if [[ -n $2 ]];then
	filename=$2
fi
path_bin=`echo ~`
path_bin=$path_bin"/tool/bin/"
#echo f:$filename
#############################################################################
if [[ -f $1 ]];then
	if [[ -f $path_bin$filename ]];then
		echo Program already exists in $path_bin
		echo Overwrite? y/n 
		read input
		if [[ $input == 'n' ]];then
			echo Job canceled.
			exit
		fi
	fi
	cp $1 $path_bin$2
	echo $path_bin
	ls -lph --color=auto  $path_bin
else
	echo $1 does not exists!
fi
